INSERT INTO MPA (RATING)
VALUES ('G');
INSERT INTO MPA (RATING)
VALUES ('PG');
INSERT INTO MPA (RATING)
VALUES ('PG-13');
INSERT INTO MPA (RATING)
VALUES ('R');
INSERT INTO MPA (RATING)
VALUES ('NC-17');

INSERT INTO GENRES (NAME)
VALUES ('Комедия');
INSERT INTO GENRES (NAME)
VALUES ('Драма');
INSERT INTO GENRES (NAME)
VALUES ('Мультфильмы');
INSERT INTO GENRES (NAME)
VALUES ('Триллер');
INSERT INTO GENRES (NAME)
VALUES ('Боевик');
INSERT INTO GENRES (NAME)
VALUES ('Документальный');
INSERT INTO GENRES (NAME)
VALUES ('Ужасы');
INSERT INTO GENRES (NAME)
VALUES ('Мистика');
INSERT INTO GENRES (NAME)
VALUES ('Романтика');
INSERT INTO GENRES (NAME)
VALUES ('Фантастика');